### ISSUE TITLE
Disable future dates and specified dates

### ISSUE THREAD

**Issue by ljw0913** [Vodolazkyi/VACalendar#11]
Hello there, thanks for creating this calendar.

Currently i am working on a project which the future dates need to be disabled. I also need to disable specified date (e.g 10 July 2018).  I am using the CalendarPopUpView. I have read through the example codes but still couldn't implement what i wanted. It will be great if you can enlighten me.

Thank you.

**Comment by Vodolazkyi** [comment]
Hi! CalendarView has a method:
`func setAvailableDates(_ availability: DaysAvailability)`

So you can pass available dates as: 
`let availableDates = DaysAvailability.some([Date()])
  calendarView.setAvailableDates(availableDates)`

Let me know if it does solve your problem
