### ISSUE TITLE
How to change date selection programmatically 

### ISSUE THREAD

**Issue by shravankumarbj** [Vodolazkyi/VACalendar#15]
Hi,

Great work. We are planning to consume your library but we have one issue. We need to select day in view programmatically. How to achieve it?

Thanks,
Star23

**Comment by Vodolazkyi** [comment]
Hi 👋 
Thank you. 
To select date you can invoke `public func selectDates(_ dates: [Date])` in calendarView
Let me know if you have more questions

**Comment by shravankumarbj** [comment]
Sorry I saw the API and wanted to close the issue myself but was not able to find the issue only to close. Thanks for you effort.
