### ISSUE TITLE
not display properly at iPhone SE screen

### ISSUE THREAD

**Issue by Binusz** [Vodolazkyi/VACalendar#2]
When I build in iPhone SE, the calendar display 6 days of week on main calendar. 
Because, self.view doesn't know own width yet. 
You need to update layout on every screen size changed.

**Comment by Vodolazkyi** [comment]
Hi @Binusz ! Is it in example project?

**Comment by Binusz** [comment]
No, not in example project. 
But the problem is frame calculated in setup function and one time only. However the frame should be updated every time layout changed.
Or may be this calendar would be compatible autolayout... So I couldn't implement it with autolayout.
