### ISSUE TITLE
A proposal for dating in the library

### ISSUE THREAD

**Issue by ATrotsenko** [Vodolazkyi/VACalendar#31]
Hi, your library is very good. I use your library in my application, and I have some problems. I need to send a request to the server with the date of the next (or previous) month, when the month has changed. And I can not find how. Can you suggest how to do this?

**Comment by Vodolazkyi** [comment]
Hi @ATrotsenko! Thank you. You can use `func monthDidChange(_ currentMonth: Date)` of `VACalendarMonthDelegate`
