### ISSUE TITLE
Set first week day to "Saturday" 

### ISSUE THREAD

**Issue by ipouya** [Vodolazkyi/VACalendar#38]
I want to use VACalendar in Iran locale , in our locale calendar first day of week is Saturday . when I set calendar.firstWeekday = 0 app will crash.

**Comment by Vodolazkyi** [comment]
Hi! Use calendar.firstWeekday = 1

**Comment by RaghavaNaidu46** [comment]
calendar.firstWeekday = 1
Above property not showing. 
how can I set to week start the day to Monday?
