### ISSUE TITLE
Dates are off in the example

### ISSUE THREAD

**Issue by rollysarmi** [Vodolazkyi/VACalendar#5]
![screenshot](https://user-images.githubusercontent.com/1249237/40894005-9adedec0-6763-11e8-951d-b2de470cc3a6.jpeg)
May 2018 should have 31 days. The date selection and supplementaries seem to be off as well. Keep up the good work! This is one of the best looking calendar framework I've used.

**Comment by Vodolazkyi** [comment]
Hi @rollysarmi ! Thanks for your report! I will look into this issue.

**Comment by Vodolazkyi** [comment]
@rollysarmi Can you please provide your locale?

**Comment by rollysarmi** [comment]
@Vodolazkyi Sorry for the late response. Local is "en_US"

**Comment by Vodolazkyi** [comment]
@rollysarmi Still can't reproduce...

**Comment by rollysarmi** [comment]
@Vodolazkyi thanks for looking into it.

**Comment by ghost** [comment]
I solved this issue by removing 

`calendar.timeZone = TimeZone(secondsFromGMT: 0)!`

from the defaultCalendar configuration
