### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [Vodolazkyi/VACalendar#9]
Good day @Vodolazkyi  I am a graphic designer and i would like to propose a logo design for your good project. Ill be doing it for free if you will allow me..Thanks and best regards! - Tobaloidee

**Comment by Vodolazkyi** [comment]
Hi @Tobaloidee! Of course, why not! we can continue our discussion in the facebook or email

**Comment by Tobaloidee** [comment]
Thanks for the positive feedback Sir..will show you here my design when done. 👍

**Comment by Tobaloidee** [comment]
here's what i came up with @Vodolazkyi  I hope you like it..Still open for suggestions

![vacalendar-01](https://user-images.githubusercontent.com/36028424/42334755-bcb62222-80b0-11e8-9b07-44d3bcde5959.png)
![vacalendar-02](https://user-images.githubusercontent.com/36028424/42334762-bfe5e7c0-80b0-11e8-98e7-ad66b9c46fa6.png)

**Comment by Vodolazkyi** [comment]
Nice! I like it! I prefer red in the white background. By the way cool idea with initials!

**Comment by Tobaloidee** [comment]
Thanks and im glad yoy liked it! Should i make a PR and upload the files already and update the readme?

**Comment by Vodolazkyi** [comment]
@Tobaloidee I would be great!

**Comment by Tobaloidee** [comment]
Here is the PR #10 @Vodolazkyi 

Thanks  a lot for accepting my contribution..best regards and goodluck to the project!

-Tobaloidee

**Comment by Vodolazkyi** [comment]
@Tobaloidee Thank you!

**Comment by Tobaloidee** [comment]
You are welcome @Vodolazkyi

Best regards!

**Comment by Tobaloidee** [comment]
Hello @Vodolazkyi  I made variations and different file formats of your logo for future use and you can download it on the link below:

[Ai-PNG-SVG](https://drive.google.com/drive/folders/1o6FiV00qttuHlLXM0M9FTGwhtbvMJVNS)

Best regards!

**Comment by Vodolazkyi** [comment]
@Tobaloidee Cool! Thank you!
